language: go

go:
- 1.12.x
- master

env:
  - GOOS=linux GOARCH=386
  - GOOS=linux GOARCH=arm

script:
    - go test -v --coverprofile=cover.out ./...
    - go get -v github.com/mattn/goveralls
    - goveralls --coverprofile=cover.out --service=travis-ci
